// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.tracy.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tracy_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tracy_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tracy_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tracy_proto_StudentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\017com.tracy.proto\"\036\n\016Stud" +
      "entRequest\022\014\n\004name\030\001 \001(\t\"\"\n\017StudentRespo" +
      "nse\022\017\n\007message\030\001 \001(\t2`\n\007Greeter\022U\n\016getSt" +
      "udentName\022\037.com.tracy.proto.StudentReque" +
      "st\032 .com.tracy.proto.StudentResponse\"\000B\'" +
      "\n\017com.tracy.protoB\014StudentProtoP\001\242\002\003HLWb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tracy_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tracy_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tracy_proto_StudentRequest_descriptor,
        new String[] { "Name", });
    internal_static_com_tracy_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tracy_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tracy_proto_StudentResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
