// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.tracy.proto;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tracy.proto.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
